### ISSUE TITLE
Today's update caused gap between header and cards

### ISSUE THREAD

**Issue by atomicpapa** [KTibow/lovelace-light-soft-ui-theme#10]
After upgrading to 0.55 a large gap has appeared between the header ( I am still running CH and not using the "new", card moc way)

![image](https://user-images.githubusercontent.com/6396499/95615152-5d4c0000-0a2d-11eb-9bd1-36d0c4f37a33.png)

After downgrading to 0.54, the gap is gone.

![image](https://user-images.githubusercontent.com/6396499/95615203-72c12a00-0a2d-11eb-901b-67f749a9c48f.png)

**Comment by KTibow** [comment]
If you remove Custom Header it should work just fine. Probably it applied margin twice, once for the default, removed header, and a second time for custom header. Anyway it's deprecated, so just uninstall it.

**Comment by atomicpapa** [comment]
> Anyway it's deprecated, so just uninstall it.

I wish it were that easy.....  I have a lot of sorting out of how I am going to make it all work without CH.  I have some dashboards that just use it to minimize the header and others that are using user exceptions to completely change what is available in the header and sidebar.

**Comment by KTibow** [comment]
Well let me know what you want me to add.
