### ISSUE TITLE
Navigation menu not shown in iOS

### ISSUE THREAD

**Issue by ThomasvZadelhoff** [KTibow/lovelace-light-soft-ui-theme#12]
I believe the Home Assistant navigation menu is not shown using this theme.

![image](https://user-images.githubusercontent.com/25841210/99901164-d4271a80-2cb4-11eb-9f63-5974bedd4b30.png)

**Comment by KTibow** [comment]
You mean the sidebar? Swipe from the left.

**Comment by KTibow** [comment]
It *did* get voted for more, but I'm lazy. https://community.home-assistant.io/t/card-mod-super-charge-your-themes/212176/119

**Comment by ThomasvZadelhoff** [comment]
No I mean this header menu bar (SEE arrow). Sometimes it's visible, sometimes its not 🤷🏻‍♂️

Dark screenshot below shows the theme when it shows, light one from issue above shows when it doensnt.

Thanks for creating this great theme btw :) 

![image](https://user-images.githubusercontent.com/25841210/99914331-fcd30280-2cfc-11eb-990a-c453ba2cc02f.jpeg)

**Comment by KTibow** [comment]
Do you mean just the blue bar, or the whole header?

**Comment by ThomasvZadelhoff** [comment]
Whole header, see the screenshot with the white theme

**Comment by KTibow** [comment]
Odd. Try upgrading HA.

**Comment by ThomasvZadelhoff** [comment]
Already am on 0.118.2. Front end version 20201111.2 - latest and cleared cache repeatedly

**Comment by KTibow** [comment]
Not getting this problem, and I’m not gonna buy an iOS device. Do you get this error in Safari, or another browser for iOS?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ThomasvZadelhoff** [comment]
I believe it happens only (or primarily) on the light version. 

All web related content on iOS devices is rendered using webkit, whatever browser you chose. But I am using the HASS app, which also uses WebKit I believe.

**Comment by KTibow** [comment]
Chrome is based on Webkit. Can you install firefox on your phone and see if you still get that error?

**Comment by ThomasvZadelhoff** [comment]
Same in firefox . Did notice dark soft ui works fine. Seem to only have this issue on the light theme. Firefox also uses WebKit though (https://developer.mozilla.org/en-US/docs/Mozilla/Firefox_for_iOS)

**Comment by KTibow** [comment]
What happens if you go to HACS, choose reinstall on the light theme, then choose the main branch instead of a version?

**Comment by ThomasvZadelhoff** [comment]
That appears to have fixed it, thanks!

**Comment by KTibow** [comment]
Okay, I'll need to make a new release.
