### ISSUE TITLE
Cards are left-aligned

### ISSUE THREAD

**Issue by brent-au** [KTibow/lovelace-light-soft-ui-theme#13]
## Expected Behavior
On a fresh install, all cards are centre-aligned.

## Actual Behavior
Cards are left-aligned.

## Observations
Following error is thrown in the console:

```
Uncaught (in promise) TypeError: Cannot read property 'length' of null
    at HTMLElement.setStyle (card-mod.js:1)
    at async HTMLElement._setTemplate (card-mod.js:1)
```

## Steps to Reproduce the Problem

(on a new Home Assistant OS install)

  1. Installed card-mod via HACS
  2. Installed 'Lovelace Soft UI light theme' via HACS
  3. Set theme to 'Lovelace Soft UI light theme'
  4. View any dashboard or create a new dashboard  

## Specifications

  - Version: v0.59
  - Platform: Home Assistant OS 2020.12.2
  - Subsystems:
    - card-mod: v2.0.3

## Debugging/Resolution attempts
- Reinstalled theme, card-mod
- Restarted multiple times
- Viewed in Chrome/Edge

## Example Screenshot
![Screenshot of erroneous alignment](https://i.imgur.com/VYnqysM.png)

**Comment by KTibow** [comment]
Try reinstalling from main.

**Comment by brent-au** [comment]
Tried reinstalling the theme from main, still having the same issue even after a restart.

**Comment by KTibow** [comment]
Huh. No issues for me, could be related to the fact that you're at `2010.12.2` but I'm at `2021.1.0b0`.
![image](https://user-images.githubusercontent.com/10727862/103441402-87632780-4c02-11eb-85a5-074b9c0c74ec.png)

**Comment by brent-au** [comment]
Ah, typo in the original, meant to say version `2020.12.2` (current stable). Updated to `2021.1.0b0`, same issue unfortunately.

**Comment by KTibow** [comment]
See any issues in the browser console?

**Comment by brent-au** [comment]
Only that noted in the observations above, I've included a screenshot for reference.

![Console Output](https://i.imgur.com/df5fdb3.png)

**Comment by baby7** [comment]
I have the same problem here，I also use HACS installation. I think the problem is here：

`#columns {
    flex-direction: column !important;
    margin: 0 auto;
    max-width: 500px;
}`

Without this code, the style is normal

**Comment by KTibow** [comment]
@baby7 Mind making a PR? Just change `theme.yaml`, run `theme_maker.py`, and create a PR for both repos.

**Comment by brent-au** [comment]
I'll look at this tonight (AEDT) if a PR isn't in.

**Comment by baby7** [comment]
Each style file has this code, I will try to PR, but I don't know where this code was used before.

**Comment by KTibow** [comment]
Edit theme.yaml and use the generator Python file.

**Comment by baby7** [comment]
OK

**Comment by baby7** [comment]
I submitted PR, but one of them didn't seem to pass the inspection

**Comment by baby7** [comment]
@KTibow I see you've updated HACS(Dark Soft UI Theme),the updated style works fine.

**Comment by KTibow** [comment]
Yeah I'm lazy. I'll get around to it.
