### ISSUE TITLE
X button partially visible, not clickable.

### ISSUE THREAD

**Issue by PrzemekSkw** [KTibow/lovelace-light-soft-ui-theme#16]
Hello, when I use that theme and edit my dashboard I cannot finish editing because X button is almost invisible and cannot click it
![Zrzut ekranu z 2021-12-06 09-56-10](https://user-images.githubusercontent.com/25219988/144816869-770cc40a-8260-4987-97bc-58c1a036e73c.png)
I have Home Assistant Core on Debian 11 miniPC.
I occur that issue on Android smartphone, tablet and laptops.

Regards.

**Comment by KTibow** [comment]
Try the theme file in https://github.com/KTibow/lovelace-light-soft-ui-theme/releases/tag/v0.61

**Comment by PrzemekSkw** [comment]
Hi @KTibow thanks for answer. Can You tell me what to do with that file? Where to copy it?
Regards.

**Comment by KTibow** [comment]
Make a new file called `soft_ui.yaml` in the `themes` directory, and copy/paste the file into that.

**Comment by PrzemekSkw** [comment]
Hi @KTibow I upgrade via HACS last time to ver. 0.61 but don't help. Do I have to remove from HACS and then add that file?

**Comment by KTibow** [comment]
0.61 didn't change anything. You don't need to remove it from HACS.

**Comment by PrzemekSkw** [comment]
Thanks, It works now :)
