### ISSUE TITLE
New theme

### ISSUE THREAD

**Issue by KTibow** [KTibow/lovelace-light-soft-ui-theme#17]
I've made a new theme, [lovelace-soft-theme](https://github.com/KTibow/lovelace-soft-theme). It's similar to this theme, but more lightweight. Feel free to go and give it a star.

Mass ping (part 1), to make sure everyone interested can see the new theme:
@qiz-li @KTibow @casuallydressedguy @farnots @eliseomartelli @emorydunn @SalGnt @TheLastZombie @JeffersonBledsoe @atomicpapa @d3centr0z @xorob0 @thorvath2207 @gonzotek @joselito11 @JanOstrowka @LucaDev @ybjlus @pmartinsb @chrisdrackett @mic-tech @brysonreece @lukastillmann @juriansluiman @JonathanTreffler @jrspowers @eriknomitch @ldec @DimasYA1 @wilsontanwh

**Comment by KTibow** [comment]
Mass ping (part 2), to make sure everyone interested can see the new theme:
@thomashermine @Max-van-Dongen @Chaphasilor @Omertron @baby7 @chasut @gruberdev @cloudedturtle @homemadestea58 @DeepCoreSystem @welcoMattic @kylehowells @jonathan81-dot @DevenLu @Patpeezy @ghayibor @Sveetly @bvp @Potato501 @olndrck @brendantay @antx-code @wax911 @P4PEES @Sagardas112 @MSM74588 @ItsEcholot

**Comment by Sagardas112** [comment]
@sagardas112
