### ISSUE TITLE
Is this theme meant to be one column ?

### ISSUE THREAD

**Issue by dotKrad** [KTibow/lovelace-light-soft-ui-theme#7]
The theme only renders one column
Using Light Soft UI
![1](https://user-images.githubusercontent.com/16595330/90326647-d876c580-df58-11ea-8c71-60a934a0d12e.png)

Using Google Light Theme
![image](https://user-images.githubusercontent.com/16595330/90326659-08be6400-df59-11ea-9626-7d12011235ef.png)

**Comment by dotKrad** [comment]
Sorry my bad, haven't read enough

**Comment by KTibow** [comment]
Yeah, it'd be nice if you could select choices and the theme could auto-detect. But yes, just remove those couple lines of code.

**Comment by KTibow** [comment]
If you use layout-card you can get around this though.
